### ISSUE TITLE
Style Support: Subway

### ISSUE THREAD

**Issue by ghost** [tierra/topicsolved#11]
I'm currently using the Subway theme (paid theme) which is based off of prosilver. I've enabled the extension, although I'm not seeing anything that allows me to mark topics as solved. Here's a link to the site: www.everythingisdown.net

**Comment by ghost** [comment]
I managed to figure it out (I'm dumb and didnt enable it on the forums.). Is there a way to add an icon to the button? It's currently showing up blank.

**Comment by tierra** [comment]
I've sent a message to your style author, who might be able to fix any issues themselves, but I won't be able to add any missing support myself for non-free styles I don't have access to.

Any styles derived from prosilver should see a prosilver-styled post button for marking topics as solved, which looks like a checkmark. Some themes intentionally hide it though to replace post button images with something else like font icons, which I've seen happen once already before. It looks like Subway also does the same thing.

You might be able to add support yourself by copying the "pbtech" folder (another style that replaced the post buttons with font icons) under "style" to the same name as your style (I'm guessing "subway"), and making modifications to that in order to show a better looking icon for your style.

**Comment by ghost** [comment]
I already tried copying over the pbtech folder and named it the same name
as my style and it still is blank. I guess I'll just wait for the style
author (or email him myself) to se if we can fix it.

Thanks!

**Comment by ghost** [comment]
I ended up getting it working. It appears the theme I was using doesn't
support the icon that was set by default. Changing the font icon made it
appear with no problem.

Thanks again!

**Comment by tierra** [comment]
If you would like your fixes included with the extension in future releases, consider submitting a new pull request with your subway files added.

Be sure to test out everything, and make sure it's all there first though.

**Comment by ghost** [comment]
Hi.I've sent you the subway files for your extension by email. Have a nice day !

**Comment by tierra** [comment]
Thanks @KomiDesign, I've added the changes.
