### ISSUE TITLE
Add Independent Post Body Subject Indicator Settings

### ISSUE THREAD

**Issue by Galixte** [tierra/topicsolved#31]
Hi @tierra,

the title is displayed both, could you remove the second, it’s useless because there is a first and because the second title is hidden behind edit/quote/delete/etc buttons on viewtopic page.

See this to understand: http://www.ezcom-fr.com/download/file.php?id=339.

I talk about this part of code in main_listener.php:

```
                        '<span style="color: #%1s">%2s</span>',
```

**Comment by tierra** [comment]
At some point, I'll probably break this out into a different indicator that can be configured independently (or hidden entirely), but it actually does represent something different from the indicator on the topic title. The indicator within the post row that you point out here actually indicates which post within the topic was marked as the "solution" to the topic. Note that you can mark the topic of unsolved, and mark a different post as the solution. Some phpBB themes don't even show the post row subject, in which case, those indicators won't be shown in those themes either.

The post row subject is supposed to wrap earlier than shown in the screenshot with the prosilver theme, but since you have so many extra post row buttons being added by new extensions, your prosilver styles actually need to be adjusted to account for a larger right margin. Here's the margin used in prosilver:

```
.has-profile .postbody h3 { margin-right: 180px; }
```

If you added some new custom CSS rule, you could fix that margin to work more appropriately in your situation using an extra 100px or so:

```
.has-profile .postbody h3 { margin-right: 280px; }
```

Ideally prosilver should avoid using a static right margin, and find a better way to float the post buttons so that the subject wraps it more naturally, but I think this is just one of those hold-overs from the 3.0 days.

Also note that this likely isn't as bad of a situation for the your users that aren't moderators or administrators since they won't have as many of those buttons shown on each post row as you do.

**Comment by Galixte** [comment]
Thanks for help. It’s Ok.
